# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b3d803a28c28121f12d98977bc4beae64e107a5fefdc3b1ca51d95061a206f929b3f223ae72aa87b278d158aad5b6bff1f4796408d54031fa29e128a17e760e

test:
  secret_key_base: 1f416ab52185d621b63b859b00e06f5dc5569c0d8fac285f366ecd6e27b35c58a9e02b31f508f3822899420a83dc38cc826c36df99916791bad5f2cb2da0999f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
